### ISSUE TITLE
v0.8 Parallel Julia execution and entity activity control seem inconsistent?

### ISSUE THREAD

**Issue by Tasqu** [spine-tools/Spine-Toolbox#2504] opened 2024-01-19 06:55 UTC
Based on some tests I did in a previous issue #2463 I identified inconsistencies with how the `Base` alternative works in `v0.8`. I created a small test system to check potential issues with parallel execution and entity activity control
[0.8-scenariotest.zip](https://github.com/spine-tools/Spine-Toolbox/files/13985148/0.8-scenariotest.zip)
Note that `print_entities.jl` needs to be linked to a `0.8-dev` `SpineInterface` locally via the `develop <spineinterface_path>` in Julia package manager.

## Test workflow description

In a small test workflow
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/338fb9bf-377e-4b44-92ab-f770fa744307)
where
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/a6791ec1-20cc-4bb8-b496-ac6a50ddd93e)
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/8855e598-07c3-4565-992a-e3551b7765b1)
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/eb463e6f-9183-4608-b791-796105b70498)
with entitity activity control
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/4dc96775-5bdc-4d18-8929-b68538694f16)
where the `print_entities.jl` simply prints all the entities, their parameter values, and parameter defaults through `SpineInterface.jl`
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/7f9f716c-c527-4b7d-9754-47c9085f5ae6)

## Problem description

The output of the parallel executions seems inconsistent, and changes if the Julia kernels are restarted. E.g.

1. `scen1`: 
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/41b1e9f3-ffab-4911-820a-f8d071cc4ee4)
worked as intended, only `scen1` entities and parameter values were output.

2. `scen2`:
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/8b06ba2c-d4f9-4b4a-9fb0-fba7cc259426)
prints results for both `scen2` and `scen3` for some reason, with the `scen3` results highlighted in the above figure.

3. `scen3`:
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/c124b836-2bc7-4aa9-ae18-dbbd00017939)
prints results for both `scen3` and `scen3` for some reason, identical with `scen2` execution. The `scen2` results are highlighted in the above figure.

4. `Base`:
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/89a671d2-58be-4390-8ed8-377637abc8ec)
Prints results similar to `scen1`, but without parameter values, as there are none defined for the `Base` alternative. However, there's no entity alternative information for `Base` either, so one would expect to get either all entities, nor none of them.

**Comment by DillonJ** [comment] 2024-01-19 13:30
@manuelma can you take a look at this please, when you're back in action? We need comprehensive tests.

**Comment by manuelma** [comment] 2024-02-05 09:33
Nice one @Tasqu 

It looks like scen2 and scen3 are sharing the same console? That can happen if you have limited the maximum number of consoles in Toolbox -> File -> Settings -> Engine settings.

Otherwise we might have a bug, but it has nothing to do with 0.8 and the interpretation of is_active it seems.

Regarding these:

> However, there's no entity alternative information for Base either, so one would expect to get either all entities, nor none of them

The default behavior for 0-D entity classes (aka object classes) is to *exclude* all entities if no entity_alternative definitions are found. @jkiviluo and I have been arguing in another issue about whether or not this behavior is nice for users who haven't read documentation. My opinion is more aligned with your expectation @Tasqu - but it would be nice to hear from more users too.

**Comment by manuelma** [comment] 2024-02-05 09:42
To explain, if an `entity` has no `entity_alternative` definitions for the winning alternative, then we look at the `active_by_default` flag of the `entity_class`. The factory setting for that flag is `false` for 0-D entity classes, which results in all entities being excluded. If you change it to `true`, the all entities will be included.

In other words, `active_by_default` is like the `default_value` of the `is_active` `parameter_definition` in 0.7.

**Comment by DillonJ** [comment] 2024-02-05 10:36
I think the main thing is that we need a consistent default default... anything else is risky and asking for trouble in my opinion... there is no reason for a user to expect different behaviour depending on the dimensionality of the class. For specific tools that might require defaults that differ for whatever reason, that tool can set active_by_default according to its own needs, but I believe toolbox should be agnostic and consistent

**Comment by Tasqu** [comment] 2024-02-05 11:49
> Nice one @Tasqu
> 
> It looks like scen2 and scen3 are sharing the same console? That can happen if you have limited the maximum number of consoles in Toolbox -> File -> Settings -> Engine settings.

Hmm, seems like it. I haven't touched the settings, but now everything seems to end up in its proper console. Hopefully this was some weirdness with the consoles that could've been resolved by restarting toolbox?

> Regarding these:
> 
> > However, there's no entity alternative information for Base either, so one would expect to get either all entities, nor none of them
> 
> The default behavior for 0-D entity classes (aka object classes) is to _exclude_ all entities if no entity_alternative definitions are found. @jkiviluo and I have been arguing in another issue about whether or not this behavior is nice for users who haven't read documentation. My opinion is more aligned with your expectation @Tasqu - but it would be nice to hear from more users too.

@manuelma  In my example `Entity alternative` is not defined for my `Base` alternative *(or the subsequent scenario)*, and I would understand if by default no entities would be printed as a result. What I don't understand is why `Base` includes the entities in `scen1 (alt1)`, despite there being no definitions stating so?

**Comment by soininen** [comment] 2024-02-05 13:48
I got this bug reproduced in a unit test.

I have an entity that is hidden by `active_by_default=False`, but is active in alternative `alt`. The entity has also a parameter value for `alt`. With those set up, the entity suddenly appears in a scenario that contains only the `Base` alternative.

**Comment by soininen** [comment] 2024-02-08 08:40
@Tasqu The issue with the Base alternative should now be fixed but I am unable to get the Julia script working. Would it be possible you checked if the entities get filtered correctly?

**Comment by Tasqu** [comment] 2024-02-09 06:37
@soininen Sure, no problem.

**Comment by Tasqu** [comment] 2024-02-09 07:06
@soininen Seems to work as intended now. `Base` scenario no longer includes any entities, as the `Entity alternative` definitions indicate.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/776c8a91-2701-42d7-8d88-ea5143221c58)

**Closed** 2024-02-19 10:55 UTC
Labels: bug, Data, 0.8-dev
