### ISSUE TITLE
is_active importer does not work anymore once the databse is migrated

### ISSUE THREAD

**Issue by e-zaline** [spine-tools/Spine-Toolbox#2864] opened 2024-06-28 08:01 UTC
Linked to issue #2748

I am using an importer to import data from an xlsx file. I have a is_active importer item, that used to translate into an Entity Alternative active parameter (since is_active is deprecated).

However, it does not work anymore. Now, this is_active importer item simply translates into the deprecated is_active, which of course does not work anymore.

<img width="391" alt="image" src="https://github.com/spine-tools/Spine-Toolbox/assets/62605130/01f5f34b-dc59-48b7-bdae-2e03e7262c2d">
<img width="488" alt="image" src="https://github.com/spine-tools/Spine-Toolbox/assets/62605130/837dc38e-d86d-4912-9976-5aa1ea1a28e7">

It used to work the first time I have updated SpineToolBox and FlexTool, but since, FlexTool have asked me to migrate the database for it to work.
```
python migrate_database.py database_name.sqlite
```
If I want it to work again, I am obliged to find a old database, copy it in place of my database, import my data, and then migrate the database. 

Strangely enough, the importer still works for this item:
<img width="482" alt="image" src="https://github.com/spine-tools/Spine-Toolbox/assets/62605130/1499adb4-037c-40d0-8882-dc5c2c2ade94">

This issue is extremely blocking for me, because the workaround with copying a database is quite tedious, and I can't add the Entity Alternative active parameter manually, because I have too many nodes and it makes SpineToolbox crash.

Thanks for your help!

**Comment by jkiviluo** [comment] 2024-07-01 06:55
The best fix is probably to implement https://github.com/spine-tools/Spine-Toolbox/issues/2748

**Comment by jkiviluo** [comment] 2024-07-01 07:34
As for workarounds, I was thinking of copy pasting into the alternative entity-alternative table, but you are saying this:
`I can't add the Entity Alternative active parameter manually, because I have too many nodes and it makes SpineToolbox crash.`

I'll make an issue about that. In my case Toolbox didn't crash (with 2000 nodes), it just freezes.

**Comment by e-zaline** [comment] 2024-07-01 08:16
Thanks @jkiviluo.
In the end this is what I am doing. It did go through for me too, but it took a really, really long time.

**Comment by soininen** [comment] 2024-07-04 06:50
is_active converts to entity alternative as long as the target database has
1. a proper parameter value list (list values must include "yes" or `true`)
2. is_active parameter definition that is associated with the value list

Can you check if the target database fulfills the requirements?

**Comment by e-zaline** [comment] 2024-07-05 10:08
Hi Antti, I am not sure if I fully understand, but in the new databases format, there is no is_active parameter anymore, so I'd say the answer is no.
<img width="479" alt="image" src="https://github.com/spine-tools/Spine-Toolbox/assets/62605130/76519751-0dfe-45a5-a22e-eb7dd31ba4d1">

**Comment by soininen** [comment] 2024-07-05 10:24
So, it looks like this is not a bug/missing feature in Toolbox. Rather, the target database must have `is_active` parameter that uses a proper value list. This is something that perhaps could be fixed in FlexTool side or you could convert the importer to use the brand new entity alternative imports.

**Closed by soininen** 2024-07-05 10:24 UTC
Labels: bug

**Comment by e-zaline** [comment] 2024-07-05 10:41
I'll definitly try the new entity alternative importer!
However I'm not sure it's a bug in FlexTool either, because the is_active paramer is supposed not to exist anymore (since it's replaced with entity alternative), no?

**Comment by jkiviluo** [comment] 2024-07-05 13:16
@soininen can you discuss with @ArttuTupala to make sure these issues wouldn't happen for FlexTool users, thanks.
