### ISSUE TITLE
DB editor filter behavior

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2134] opened 2023-05-23 16:27 UTC
At present we can use multiple widgets to choose what parameters are shown in the parameter view. It's great, but it's also bit confusing. E.g. if I have an alternative selected in the Alternative tree and then I select a scenario from the Scenario Tree, I will see both parameters for both selections at the same time. However, if I choose a new alternative in the Alternative Tree, I won't see the old alternative parameters unless I use Ctrl-select. I think this latter behavior is much more expected also across the different widgets. 

So, desired behavior:
- If I choose an alternative from Alternative Tree, then selection from Scenario Tree should be cleared (unless using CTRL-select).
- Similarly, if I choose a class from object tree, other selections (relationship/entity, alternative, and scenario) should be cleared unless using CTRL-select
- SHIFT-SELECT should not work across widgets (the older selections will be forgotten) - for them to be included user needs to use CTRL-SHIFT-select - that would mean that CTRL is clearly an additive selection and without it, you don't add.

**Comment by jkiviluo** [comment] 2023-06-01 09:46
Very nice! Much nicer to work this way.

I notice that if I have selected a scenario and after that select the root in 'relationship' class, I will not see all relationship parameters. It's maybe a separate bug.

**Comment by manuelma** [comment] 2023-06-01 09:55
Yeah, seems like a very nice change!

Although I still think that, since this is a feature and not a bug-fix, we could have done it in 0.8. I know I said it was ok to do this kind of changes and notify me so I can merge. Maybe it's still ok. But this one really messes with a lot of the new stuff.

**Comment by jkiviluo** [comment] 2023-06-01 12:06
I guess I was not thinking, sorry. Hold the merge - there are some issues that still need to be fixed here. Maybe @PiispaH could merge it to 0.8? Or would that be prone to mess up your work?

**Comment by jkiviluo** [comment] 2023-06-01 12:07
Some cross-selections do not work yet as expected:

- Choosing both object and relationship at the same time
- Choosing alternatives and then object class and then objects from another object class

**Comment by soininen** [comment] 2023-06-02 06:06
> the most painful thing is whenever we modify ui files and the corresponding py file in master

Then, we should modify the .ui files only when it is absolutely necessary.

I usually ignore the conflicts in the generated .py files because once the corresponding .ui file is fixed, the .py file can be recreated by running `bin/build_ui`.

**Comment by PiispaH** [comment] 2023-06-08 09:56
Yeah there are many things wrong with my previous implementation and I've been having a hard time with them. Might be that in order to get everything working, big changes would be needed, which would then probably cause a lot of issues with the entity branch.

**Comment by manuelma** [comment] 2023-06-08 10:42
I see, that's a pity. At the beginning I thought this was a good idea but now I really want to have the double filtering.

I think we need to keep all selections alive, never clear any, and the result in that case will be that the parameter tables are filtered by the intersection of all filters. The original spec from @jkiviluo that involves extending selections across multiple views with Ctrl+click also feels a bit awkward and non-standard.

So my proposal is let each view have their own selection regardless of any other selections in other views. So basically revert what was done here in the nicest possible way.

**Comment by manuelma** [comment] 2023-06-08 13:14
@jkiviluo what do you think?

**Comment by jkiviluo** [comment] 2023-06-08 16:24
I really feel the awkwardness is the other way around. I go choose something on a list and then I realize I don't see what I expect to see, because there is another filter still active. I need to go and deselect the filter from the other list and then do the original intent again. I do this all the time...

The old system often requires two clicks when it could be achieved with one click (whenever there is some filter somewhere active). When one needs to double filter, it's natural to use ctrl-click, because it's the standard way of selecting multiple items (and also the way it works within a list).

I fully agree that the cross/double filtering needs to work. It is already partially working (choosing alternative and object does what it should do).

Maybe this could be left as it is now in the 0.7 branch (not being able to select both unit and relationship or class together with entities from another class are not so big things IMHO)? All of this could be then fully fixed in v0.8 once it becomes more mature. Part of it will get resolved naturally there, since there is no need to manage both units and relationships - just entities.

It's also ok to revert for now, but I'd like to see the full change in v0.8 at some point.

**Comment by DillonJ** [comment] 2023-06-08 17:44
Would the option to toggle filter behaviour over complicate things?

**Comment by manuelma** [comment] 2023-06-09 06:37
> I fully agree that the cross/double filtering needs to work. It is already partially working

**Comment by PiispaH** [comment] 2023-06-09 07:50
Ok, I can fix the issues with double filtering that I think I can do reasonably easily for 0.7 and then in 0.8 see if the remaining issues are really issues anymore.

**Comment by PiispaH** [comment] 2023-06-12 12:24
> * Choosing alternatives and then object class and then objects from another object class
This is now fixed and selecting objects and relationships at the same time is also now possible, even though then only the filtered relationships are currently shown in the parameter views.

**Comment by manuelma** [comment] 2023-06-12 14:07
Nice job @PiispaH 

I am now merging this into my branch. I am not sure how to solve some conflicts so we probably will have to come back to this at some point to make sure it all works as intended in my branch too.

**Comment by PiispaH** [comment] 2023-09-07 10:13
Currently the filters show the union of the selected items when all of the selections are either entity classes or entities but not a mix of them. Is the wanted behavior for selections of entity classes and entities like in the image below, where all items related to entity class A are shown and also all items that have entity ca in them? @jkiviluo @manuelma

![possible_behavior](https://github.com/spine-tools/Spine-Toolbox/assets/98282892/ebd21776-89ca-4912-a24a-06e64a738c84)

**Comment by DillonJ** [comment] 2023-09-07 12:23
Yeah, that makes sense to me - the intersection would always be an empty set, so I think this would be the only way to interpret what the user wants to see in this case

**Comment by jkiviluo** [comment] 2024-05-03 09:04
@manuelma could @PiispaH take over? Any suggestions for him?

**Comment by manuelma** [comment] 2024-05-03 09:27
I think I forgot to close this. It was working well and fast enough after some changes I did and I think after that @soininen fixed my fix and also benchmarked it. So we are ok here I believe, good to close. Please reopen if I'm wrong.

**Closed by manuelma** 2024-05-03 09:27 UTC
Labels: Feature, UI, high priority
