### ISSUE TITLE
the latest dev not working with conda python 3.12

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/Spine-Toolbox#2810] opened 2024-05-30 12:48 UTC
As the title indicates, running `spinetoolbox` fails with "Exit Code 1" with the installations below. The same spine packages work with conda python 3.11.

Python: Python 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:42:21) [MSC v.1916 64 bit (AMD64)] on win32
spine_engine              0.25.0.dev8+g106b313  
spine_items                0.22.2                
spinedb_api               0.32.0.dev1+gdfbb3b0 
spinetoolbox              0.9.0.dev1+g5a5f652ea

**Comment by jkiviluo** [comment] 2024-08-15 08:56
@PekkaSavolainen would you have a clue and does this reproduce?

**Comment by PekkaSavolainen** [comment] 2024-08-16 09:51
@nnhjy Could not reproduce. Works fine in an miniconda env after installing Visual C++ Build Tools (pip install -r requirements.txt fails without them).

Win 11
Conda 24.5.0
spinetoolbox 0.9.0.dev66
spinedb_api 0.32.0.dev72+g6130c3b
spine_engine 0.25.0.dev7+gcab35ff
spine_items 0.23.0.dev21+g4ce33aa
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]

**Comment by nnhjy** [comment] 2024-08-26 08:42
Thanks @ptsavol.
A dirty fix to the issue could be to delete the original conda virtual environment (one was created with Python 3.11 and upgraded to 3.12) and create a new one with Python 3.12.
So it doesn't seem pertaining to the new python version *per se* but to a change of python (major?) version (3.1x --> 3.1y) in conda.

It could be of help to give a hint on such a case if no proper fix can be found for now.

**Comment by ptsavol** [comment] 2024-08-26 09:12
Ok, thanks for the additional info @nnhjy. I've never tried upgrading a conda env Python. I just make a new env for each Python version. Did you reinstall Spine Toolbox requirements after upgrading Python? I think the issue you encountered may have happened because there are no wheels for the gdxcc package for Python 3.12 as per issue #2524 (which will be fixed soon(ish)!).

**Comment by nnhjy** [comment] 2024-08-26 12:58
> Did you reinstall Spine Toolbox requirements after upgrading Python?
I tried that with your previous advice. No error occurred, but it didn't resolve the issue, either.

**Comment by jkiviluo** [comment] 2024-11-05 07:53
I think this should be resolved by now. Closing.

**Closed by jkiviluo** 2024-11-05 07:53 UTC
Labels: bug
