### ISSUE TITLE
Exporter multiple file advertising can be a bit confusing

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1560] opened 2021-10-05 13:03 UTC
If I select CSV as the format for a exporter spec and then define a mapping that generates multiple tables, when running, the exporter will write one CSV file per table. This is a bit surprising, but fine I guess. The filename I enter in the exporter properties though (say it's xxx.csv) doesn't get considered at all.

But then if I connect the Exporter to a Tool, I see something more surprising in available resources. I see a resource called xxx.csv (the filename I entered in the exporter properties) that can be expanded. If I expand it, I see all the CSV files generated by the exporter.

If I put the xxx.csv resource in the tool command line arguments, I see another surprising thing: the command line argument that the tool receives is all the CSV filenames joined by a space character.

All this feels kind of arbitrary and difficult to use. I don't know if I'm missing a special use-case, but I would prefer if the CSV export format would always write one single file. If the mapping generates multiple tables, then it either fails or concatenates the tables vertically somehow, but in the same file (the one the user entered in the Exporter properties). This would make resource advertising cleaner and more predictable.

And we could add datapackage as an additional export format, that does what the CSV format is doing now, but also writes the datapackage.json file (or whatever name the user entered in the Exporter properties) that is the file that gets advertised.

Any thoughts? @soininen @jkiviluo @ererkka @PekkaSavolainen ?

**Comment by soininen** [comment] 2021-10-06 05:15
The multiple output files feature is indeed a use case that we should keep. In this case the output file name should really be considered as a *label* but unfortunately, this is not reflected in Exporter's properties tab. I've recognized is as a problem but have overlooked it this far. The way the label is expanded into multiple space delimited paths when used in command line arguments works as intended. However, I agree we should give a hint to the user that this is going to happen. Would be nice if the delimiter was a setting, too.

In addition to making the 'output file name' reflect its label-likeness and making the command line argument usage more apparent, it would be OK to have an option in Exporter to export a single CSV file, too. I just haven't encountered that use case yet. Making an optional datapackage out of the files is not a bad idea, either, we just cannot except Tools to understand such high level concepts.

**Comment by jkiviluo** [comment] 2021-10-06 05:26
I was going to write about that. E.g. in FlexTool we write multiple csv files that are just put into the directory and the tool expects to find them there (they are input files in the tool spec). The file names are not passed as resources.

I think there is a related proposal concerning the command line argument in https://github.com/Spine-project/Spine-Toolbox/issues/1555. I'm not 100% what you mean by delimiter in this case though.

Optional datapackage would be nice. At least importer can understand it.

**Comment by manuelma** [comment] 2021-10-06 05:36
The datapackage idea might also cover the FlexTool use case you describe @jkiviluo 
It will write all the CSV files to a certain folder as the current CSV exporter does. But on top of that, it will write a datapackage.json.
The tool should be able to parse the datapackage.json to find the location of the CSV files. So you'd just need to select datapackage instead of CSV in the export format combobox.

What kind of tool wouldn't be able to parse a datapackage.json file? Are we talking about GAMS tools?

Anyways, I really think we should make it clearer to the user. The current label idea is a bit unintuitive, and I think users would prefer the datapackage? The datapackage is also well documented. Also it would make things more balanced with the Importer.

**Comment by soininen** [comment] 2021-10-06 05:41
> I'm not 100% what you mean by delimiter in this case though.

I was thinking that some programs may want their file paths as comma-separted list but I'm not sure how often you encounter those.

> What kind of tool wouldn't be able to parse a datapackage.json file?

Any script/executable that just doesn't use datapackages?

**Comment by manuelma** [comment] 2021-10-06 05:48
> Any script/executable that just doesn't use datapackages?

Datapackage is just JSON. So you're thinking of tools that aren't able to parse a JSON file, but are able to split a string from the command line argument. I'm asking if this use case is relevant, and in that case, how could we make it nicer? Maybe it's just about changing from 'filename' to 'label' in the exporter properties?

**Comment by soininen** [comment] 2021-10-06 06:03
> Datapackage is just JSON.

We still cannot expect Tool scripts to parse it.

> but are able to split a string from the command line argument.

There is really no splitting as the Tool script just receives a bunch of paths as its command line arguments, e.g. for a Python Tool `argv[1:]` could be a list of one or more paths. This is normal operation and numerous scripts/executables take such file lists as their arguments. See for example *NIX `cp` command: `cp file1 file2 file3 /target/`

> how could we make it nicer? Maybe it's just about changing from 'filename' to 'label' in the exporter properties?

filename -> label would be the first step. I think we want some other indicators as well. Maybe improve tooltips and make *transiend file resources* and *file resource packs* appear in italics in Tool/Importer properties?

**Comment by manuelma** [comment] 2021-10-06 06:51
> For users we should make clear that there are two ways that tools can access resources from the previous item: arguments and files.

Here I am discussing about arguments that are so-called file packs. I want to make them more understandable. The other issues you describe @jkiviluo are interesting but I think they are separate.

**Comment by manuelma** [comment] 2021-10-06 07:06
> Sincere apologies for that! I think we can fix that, though, and split the files as separate command line arguments correctly. 

No worries! Well, if you can fix that, and we do the filename -> label thing in Exporter properties too, then I think we would have solved 80% of this issue. Filename -> label could also help improving the connection between Exporter properties and spec, because the filename could be just label + extension, where extension comes automatically from the export format?

**Comment by soininen** [comment] 2021-10-06 07:18
Alright, I'll fix the properties tab and Tool command line arguments and check that User guide is up-to-date.  Other things to consider:

- An option to write tables to a single .csv file. Exporter would need to support output format-specific options (also in `spinedb_api` side). We'd need to think what to do with table names in this case: write them as table separating lines in the file or ...?
- An option to pack the files in a datapackage. Useful at least for Importers, though we'd want to have the merged Exporter-Importer project item in the long run.

**Comment by manuelma** [comment] 2021-10-06 07:50
> Datapackage makes more sense, but maybe not a high priority if we manage to merge exporter/importer near-term.

What is this importer/exporter merging? It is a new project item, right?

I think datapackage is useful on its own, not just to feed the importer. Python and Julia tools, which I presume will become more and more prominent in the future, should prefer this option. And it's relatively easy to support in the Exporter, so I would give it some priority.

**Comment by soininen** [comment] 2021-10-06 09:17
> What is this importer/exporter merging? It is a new project item, right?

A new project item, yes. For data transformations like reshaping entities/relationships/parameter value dimensions. Currently, some projects connect Exporters and Importers back-to-back to achieve this but it would make sense to have a dedicated project item.

**Comment by jkiviluo** [comment] 2023-02-10 09:15
@soininen Is there something here to keep open? If so, maybe a clear statement about that would be helpful.

**Comment by soininen** [comment] 2023-02-10 10:35
TODOs here:

- [ ] Connect Exporter's Output file in the properties tab to Format in the specification editor (sniff output format from the file name, update file name extension when format changes)
- [ ] When resource label contains multiple files, break them into separate command line arguments in Tool

**Closed** 2023-02-15 12:09 UTC
Labels: enhancement, Data import/export
