### ISSUE TITLE
Filter parameter values by entity sub tree selection

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2945] opened 2024-10-01 15:43 UTC
The behqviour of v0.7 was to filter when a specific relationship was selected in the tree. Now, the only effect is to complete the entitybyname field. I think it should also filter the parameter pane to show only parameters associated with the selected entity

See below image. I'm forced to visually process the entityby name field to divine what parameter values are associated with the selected multi d entity (relationship)

I really miss the filtering behaviour

![image](https://github.com/user-attachments/assets/80991112-ad00-46e7-bd83-c71c2790aae8)

**Comment by jkiviluo** [comment] 2024-10-07 09:23
Duplicate of https://github.com/spine-tools/Spine-Toolbox/issues/2951

**Closed by jkiviluo** 2024-10-07 09:22 UTC
Labels: enhancement, DB editor
