### ISSUE TITLE
Group node add or remove members

### ISSUE THREAD

**Issue by RowanPeng** [spine-tools/Spine-Toolbox#2219] opened 2023-07-28 13:52 UTC
Hi there,

I found an issue that it cannot edit the members of a group node. Every time I try to add new nodes or remove the existing nodes, the Spinetoolbox window would flash out. I was wondering if this is the issue relating to my computer or the tool.

Regards,

Yuwen

**Comment by mihlema** [comment] 2023-07-28 14:43
Hi @RowanPeng thanks for opening this issue. I believe it's more related to Spine Toolbox than to SpineOpt, and have therefore transferred it this repository.

**Comment by tarskul** [comment] 2023-07-28 14:45
I mean the terminal of your pc. Normally that opens together with spine toolbox. Or do you mean that spine toolbox crashes? In that case the terminal will dissappear as well (although in linux you can trick the terminal in staying by opening another tab in the terminal).

If toolbox crashes than the issue is probably more related to Spine Toolbox rather than SpineOpt and we should transfer this issue. [edit: it seems that @mihlema was already thinking one step ahead]

**Comment by RowanPeng** [comment] 2023-07-28 18:53
Spine-toolbox crashed and then the command window shows like this.
<img width="899" alt="image" src="https://github.com/spine-tools/Spine-Toolbox/assets/123334582/9bea129d-02a2-463b-bd1c-80233f004892">

**Comment by soininen** [comment] 2023-07-31 05:32
@RowanPeng Can you provide the exact steps that led to Toolbox crash? Is "group node" an object group? How did you edit it? For me the Manage members dialog does not crash Toolbox. Clicking the OK button does not make any changes to the group members, though, so we do have an issue there.

**Comment by RowanPeng** [comment] 2023-07-31 07:04
@soininen Yes, you are right. I can add and remove node to a group_node, and there is also a window in the right_bottom_corner saying "successfully". However, the problem is when I go back to check the group member under the group_node, nothing is changed. And when I click the commit button, it will crash.

**Closed** 2023-08-02 14:04 UTC
Labels: bug
